// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     email.avsc
 *     email_activate_user.avsc
 */

package schemas

import (
	"io"
)

type EmailActivateUser struct {
	Name        string
	ActivateUrl string
}

func DeserializeEmailActivateUser(r io.Reader) (*EmailActivateUser, error) {
	return readEmailActivateUser(r)
}

func NewEmailActivateUser() *EmailActivateUser {
	v := &EmailActivateUser{}

	return v
}

func (r *EmailActivateUser) Schema() string {
	return "{\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"activateUrl\",\"type\":\"string\"}],\"name\":\"EmailActivateUser\",\"namespace\":\"si.rso.bicycle.schemas\",\"type\":\"record\"}"
}

func (r *EmailActivateUser) Serialize(w io.Writer) error {
	return writeEmailActivateUser(r, w)
}
