// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     email.avsc
 *     email_activate_user.avsc
 */

package schemas

type EmailType int32

const (
	EmailTypeACTIVATEUSER EmailType = 0
)

func (e EmailType) String() string {
	switch e {
	case EmailTypeACTIVATEUSER:
		return "ACTIVATE_USER"

	}
	return "unknown"
}
