// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     email.avsc
 *     email_activate_user.avsc
 */

package schemas

import (
	"io"
)

type Email struct {
	Type  EmailType
	Email string
	Data  []byte
}

func DeserializeEmail(r io.Reader) (*Email, error) {
	return readEmail(r)
}

func NewEmail() *Email {
	v := &Email{}

	return v
}

func (r *Email) Schema() string {
	return "{\"fields\":[{\"name\":\"type\",\"type\":{\"name\":\"EmailType\",\"symbols\":[\"ACTIVATE_USER\"],\"type\":\"enum\"}},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"data\",\"type\":\"bytes\"}],\"name\":\"Email\",\"namespace\":\"si.rso.bicycle.schemas\",\"type\":\"record\"}"
}

func (r *Email) Serialize(w io.Writer) error {
	return writeEmail(r, w)
}
