// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     sms.avsc
 *     sms_mfa.avsc
 */

package schemas

import (
	"io"
)

type Sms struct {
	Type        SmsType
	PhoneNumber string
	Data        []byte
}

func DeserializeSms(r io.Reader) (*Sms, error) {
	return readSms(r)
}

func NewSms() *Sms {
	v := &Sms{}

	return v
}

func (r *Sms) Schema() string {
	return "{\"fields\":[{\"name\":\"type\",\"type\":{\"name\":\"SmsType\",\"symbols\":[\"MFA\"],\"type\":\"enum\"}},{\"name\":\"phone_number\",\"type\":\"string\"},{\"name\":\"data\",\"type\":\"bytes\"}],\"name\":\"Sms\",\"namespace\":\"si.rso.bicycle.schemas\",\"type\":\"record\"}"
}

func (r *Sms) Serialize(w io.Writer) error {
	return writeSms(r, w)
}
