// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     sms.avsc
 *     sms_mfa.avsc
 */

package schemas

import (
	"io"
)

type SmsMfa struct {
	Code string
}

func DeserializeSmsMfa(r io.Reader) (*SmsMfa, error) {
	return readSmsMfa(r)
}

func NewSmsMfa() *SmsMfa {
	v := &SmsMfa{}

	return v
}

func (r *SmsMfa) Schema() string {
	return "{\"fields\":[{\"name\":\"code\",\"type\":\"string\"}],\"name\":\"SmsMfa\",\"namespace\":\"si.rso.bicycle.schemas\",\"type\":\"record\"}"
}

func (r *SmsMfa) Serialize(w io.Writer) error {
	return writeSmsMfa(r, w)
}
