// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     sms.avsc
 *     sms_mfa.avsc
 */

package schemas

type SmsType int32

const (
	SmsTypeMFA SmsType = 0
)

func (e SmsType) String() string {
	switch e {
	case SmsTypeMFA:
		return "MFA"

	}
	return "unknown"
}
